/**
 * Project Feature & UI Identity Registry — the sole definition of UI identities.
 *
 * `data-ui-id` is the DOM binding for these records. IDs are permanent
 * conceptual identities, not labels, list positions, React keys, or render order.
 * Repeated instances of a list-row/control template may share the template ID;
 * attach a domain-specific `data-ui-instance` when a particular row matters.
 */

import { FEATURE_REGISTRY, type FeatureId, type RegistryStatus } from './feature-registry';

export type UIKind =
  | 'route'
  | 'shell'
  | 'navigation'
  | 'toolbar'
  | 'panel'
  | 'card'
  | 'section'
  | 'list'
  | 'list-item'
  | 'dialog'
  | 'menu'
  | 'form'
  | 'input'
  | 'select'
  | 'checkbox'
  | 'button'
  | 'action'
  | 'control'
  | 'filter'
  | 'drag-handle'
  | 'inspector';

export interface UIRegistryEntry {
  id: string;
  kind: UIKind;
  name: string;
  featureId: FeatureId;
  parentId: string;
  route: string;
  component: string;
  sourceFile: string;
  description: string;
  status: RegistryStatus;
  behavior: string;
  constraints: string;
  dependencies: readonly string[];
  relatedIds: readonly string[];
  codeReferences: readonly string[];
}

const active = (entry: Omit<UIRegistryEntry, 'status'>): UIRegistryEntry => ({ ...entry, status: 'active' });

export const UI_REGISTRY = [
  // Route identities: each route ID is present on the page's top-level DOM node.
  active({ id: 'A020', kind: 'route', name: 'Editor Route', featureId: 'A001', parentId: 'A001', route: '/editor', component: 'EditorPage', sourceFile: 'src/app/(dashboard)/editor/page.tsx', description: 'صفحة تحرير المستند والاختلافات.', behavior: 'تفتح المستند المحلي وتعرض أدوات التحرير والرسم.', constraints: 'تغيير المعرف لا يتم عند نقل المسار أو إعادة تصميم الصفحة؛ يظل A001 هوية الميزة.', dependencies: [], relatedIds: ['A100', 'A101', 'A107', 'A111', 'A113', 'A114'], codeReferences: ['useEditorStore', 'useKeyboardShortcuts'] }),
  active({ id: 'A021', kind: 'route', name: 'Engine Studio Route', featureId: 'A002', parentId: 'A002', route: '/studio', component: 'EngineStudioPage', sourceFile: 'src/app/(dashboard)/studio/page.tsx', description: 'صفحة سياسات وإعدادات المحرك.', behavior: 'تدير أقسام استوديو المحرك من ملف الإعداد النشط.', constraints: 'لا تكرر منطق resolver داخل الصفحة.', dependencies: [], relatedIds: ['A150', 'A155', 'A158', 'A163', 'A169'], codeReferences: ['useEngineStudioStore', 'executionOrderImpact'] }),
  active({ id: 'A022', kind: 'route', name: 'Quran Route', featureId: 'A003', parentId: 'A003', route: '/quran', component: 'QuranPage', sourceFile: 'src/app/(dashboard)/quran/page.tsx', description: 'قارئ المصحف وعرض التشجير النهائي.', behavior: 'يعرض السورة المختارة وآياتها وما حُفظ أو اشتُق لها من تشجير.', constraints: 'لا يغيّر المستند عند العرض؛ التعديل يتم عبر رابط المحرر.', dependencies: [], relatedIds: ['A180', 'A182', 'A187'], codeReferences: ['listDocuments', 'surahAyahsWithTashjeer'] }),
  active({ id: 'A023', kind: 'route', name: 'Tracking Route', featureId: 'A004', parentId: 'A004', route: '/tracking', component: 'TrackingPage', sourceFile: 'src/app/(dashboard)/tracking/page.tsx', description: 'صفحة تتبع المصدر والتصحيح وقرار المحرك.', behavior: 'تجمع بيانات المستندات والتجاوزات وتتيح التصفية وفتح الأثر.', constraints: 'واجهة قراءة؛ لا تُعدّل مستندات المستخدم مباشرة.', dependencies: [], relatedIds: ['A200', 'A201', 'A203', 'A204'], codeReferences: ['readTrackingRows', 'trackingSummary', 'resolveDifference'] }),
  active({ id: 'A024', kind: 'route', name: 'Variant Index Route', featureId: 'A005', parentId: 'A005', route: '/variants', component: 'VariantsIndexPage', sourceFile: 'src/app/(dashboard)/variants/page.tsx', description: 'فهرس الاختلافات والقواعد العامة.', behavior: 'يصفّي السجلات ويتيح تحرير البيانات المسجلة أو فتحها في المحرر.', constraints: 'لا تُنسخ القواعد العامة إلى مستند الآية عند العرض.', dependencies: [], relatedIds: ['A220', 'A221', 'A222', 'A223'], codeReferences: ['readGlobalRules', 'describeGlobalPattern'] }),
  active({ id: 'A025', kind: 'route', name: 'Qiraat Catalog Route', featureId: 'A006', parentId: 'A006', route: '/qiraat', component: 'QiraatPage', sourceFile: 'src/app/(dashboard)/qiraat/page.tsx', description: 'استعراض القراءات العشر.', behavior: 'يبحث في قائمة القراءات ويعرض تفاصيل القراءة المحددة.', constraints: 'مصدر القراءة هو بيانات المشروع الحالية.', dependencies: [], relatedIds: ['A230', 'A231', 'A232'], codeReferences: ['src/data/qiraat-data/qiraat.ts'] }),
  active({ id: 'A026', kind: 'route', name: 'Readers Route', featureId: 'A007', parentId: 'A007', route: '/readers', component: 'ReadersPage', sourceFile: 'src/app/(dashboard)/readers/page.tsx', description: 'صفحة ملفات القراء وإدارتها.', behavior: 'تعرض نموذج الملف وقائمة القراء وإجراءات الصفحة.', constraints: 'لا تفترض وجود backend؛ اربط التغيير بالتنفيذ الموجود فقط.', dependencies: [], relatedIds: ['A240', 'A241', 'A242'], codeReferences: ['ReadersPage'] }),
  active({ id: 'A027', kind: 'route', name: 'Review Route', featureId: 'A008', parentId: 'A008', route: '/review', component: 'ReviewPage', sourceFile: 'src/app/(dashboard)/review/page.tsx', description: 'قائمة المراجعة العلمية.', behavior: 'تعرض السجلات القابلة للمراجعة وإجراءات حالتها.', constraints: 'حافظ على بيانات المصدر وحالات المراجعة الحالية.', dependencies: [], relatedIds: ['A250', 'A251', 'A252'], codeReferences: ['document-store'] }),
  active({ id: 'A028', kind: 'route', name: 'Administration Route', featureId: 'A009', parentId: 'A009', route: '/admin', component: 'AdminPage', sourceFile: 'src/app/(dashboard)/admin/page.tsx', description: 'إدارة كتالوج القراء والرواة والطرق.', behavior: 'تبدّل بين كتالوج الإرسال وتبويب قديم يحيل إعداد المحرك إلى Studio.', constraints: 'تبويب إعدادات المحرك هنا رابط توافق قديم وليس مصدرا مستقلا.', dependencies: [], relatedIds: ['A260', 'A261', 'A262'], codeReferences: ['readTransmissionCatalog', 'saveTransmissionCatalog'] }),
  active({ id: 'A029', kind: 'route', name: 'Settings Route', featureId: 'A010', parentId: 'A010', route: '/settings', component: 'SettingsPage', sourceFile: 'src/app/(dashboard)/settings/page.tsx', description: 'صفحة إعدادات مساحة العمل.', behavior: 'تعرض خيارات الإعداد وإدارة درجات القوة.', constraints: 'لا تغيّر إعدادات المحرك من هذه الصفحة إلا عبر مصدرها المعتمد.', dependencies: [], relatedIds: ['A270', 'A271'], codeReferences: ['StrengthDegreesManager'] }),
  active({ id: 'A030', kind: 'route', name: 'Statistics Route', featureId: 'A011', parentId: 'A011', route: '/statistics', component: 'StatisticsPage', sourceFile: 'src/app/(dashboard)/statistics/page.tsx', description: 'لوحة الإحصاءات والتغطية.', behavior: 'تعرض أعدادا مشتقة وروابط مراجعة ذات صلة.', constraints: 'عرض للقراءة فقط؛ الأرقام مشتقة من ملفات البيانات الحالية.', dependencies: [], relatedIds: ['A280'], codeReferences: ['listDocuments', 'TOTAL_AYAHS'] }),
  active({ id: 'A031', kind: 'route', name: 'Public Home Route', featureId: 'A012', parentId: 'A012', route: '/', component: 'HomePage', sourceFile: 'src/app/page.tsx', description: 'صفحة المشروع العامة.', behavior: 'تعرض قصة المنتج وبيانات العرض الحقيقية وروابط الانتقال.', constraints: 'المخطط التجريبي مبني من بيانات المشروع عبر buildShowcase.', dependencies: [], relatedIds: ['A290', 'A291'], codeReferences: ['buildShowcase'] }),
  active({ id: 'A032', kind: 'route', name: 'Local Sign-in Route', featureId: 'A013', parentId: 'A013', route: '/login', component: 'LoginPage', sourceFile: 'src/app/login/page.tsx', description: 'نموذج الدخول المحلي.', behavior: 'يتحقق من الحقول ويحفظ جلسة في localStorage ثم ينتقل إلى المحرر.', constraints: 'لا يرسل البريد أو كلمة المرور إلى خدمة خارجية.', dependencies: [], relatedIds: ['A340', 'A341', 'A342', 'A344'], codeReferences: ['localStorage.setItem("tashjeer-session")'] }),

  // Editor workspace and high-value controls.
  active({ id: 'A100', kind: 'shell', name: 'Editor Canvas Workspace', featureId: 'A001', parentId: 'A020', route: '/editor', component: 'EditorPage', sourceFile: 'src/app/(dashboard)/editor/page.tsx', description: 'منطقة العمل المركزية التي تعرض نص الآية ورسم التشجير ومساحة التفاعل.', behavior: 'تحتوي لوحة TashjeerCanvas داخل السطح المركزي للمحرر.', constraints: 'تغييرات العرض لا تغيّر state أو المحرك من تلقاء نفسها.', dependencies: ['A111'], relatedIds: ['A107', 'A113', 'A114'], codeReferences: ['TashjeerCanvas', 'useEditorStore'] }),
  active({ id: 'A101', kind: 'toolbar', name: 'Editor Toolbar', featureId: 'A001', parentId: 'A020', route: '/editor', component: 'EditorToolbar', sourceFile: 'src/components/editor/EditorToolbar.tsx', description: 'أدوات التحديد والعرض والحفظ والتصدير والتحكم باللوحات.', behavior: 'يغيّر أداة التحرير أو خيارات العرض وينفذ الحفظ وأوامر المستند.', constraints: 'أزرار العرض منفصلة عن business logic للمحرك.', dependencies: ['A103', 'A104', 'A135', 'A136'], relatedIds: ['A102', 'A137'], codeReferences: ['useEditorStore', 'saveEngineSettings'] }),
  active({ id: 'A102', kind: 'control', name: 'Editor Tool Palette', featureId: 'A001', parentId: 'A101', route: '/editor', component: 'EditorToolbar', sourceFile: 'src/components/editor/EditorToolbar.tsx', description: 'أزرار تحديد وتعليم ومسح المواضع.', behavior: 'تعيّن الأداة الحالية أو نمط تعليم الكلمات/الحروف.', constraints: 'لا ينشئ العنصر سجلا حتى تنفّذ عملية الإنشاء من واجهتها المختصة.', dependencies: [], relatedIds: ['A116', 'A111'], codeReferences: ['setTool', 'setMarkingMode'] }),
  active({ id: 'A103', kind: 'button', name: 'Undo Action Button', featureId: 'A001', parentId: 'A101', route: '/editor', component: 'EditorToolbar', sourceFile: 'src/components/editor/EditorToolbar.tsx', description: 'زر التراجع عن آخر عملية مستند.', behavior: 'يستدعي undo من editor-store عند توفر سجل سابق.', constraints: 'يحافظ على مكدس التراجع الموحد؛ لا ينشئ سجلا موازيا.', dependencies: [], relatedIds: ['A104', 'A105'], codeReferences: ['undo', 'canUndo'] }),
  active({ id: 'A104', kind: 'button', name: 'Redo Action Button', featureId: 'A001', parentId: 'A101', route: '/editor', component: 'EditorToolbar', sourceFile: 'src/components/editor/EditorToolbar.tsx', description: 'زر إعادة العملية التي تم التراجع عنها.', behavior: 'يستدعي redo من editor-store عند توفر سجل مستقبلي.', constraints: 'يحافظ على مكدس التراجع الموحد؛ لا ينشئ سجلا موازيا.', dependencies: [], relatedIds: ['A103', 'A105'], codeReferences: ['redo', 'canRedo'] }),
  active({ id: 'A105', kind: 'menu', name: 'Editor Operation History Menu', featureId: 'A001', parentId: 'A101', route: '/editor', component: 'HistoryControls', sourceFile: 'src/components/editor/HistoryControls.tsx', description: 'قائمة الحالات المحفوظة في تاريخ المستند.', behavior: 'تعرض snapshots وتتيح القفز بينها بعد تأكيد.', constraints: 'تعيد استعمال تاريخ editor-store ولا تملك سجل أوامر منفصلا.', dependencies: ['A103', 'A104'], relatedIds: ['A101'], codeReferences: ['past', 'future', 'confirmAction'] }),
  active({ id: 'A106', kind: 'menu', name: 'Unified Clipboard Menu', featureId: 'A001', parentId: 'A101', route: '/editor', component: 'ClipboardControls', sourceFile: 'src/components/editor/ClipboardControls.tsx', description: 'قائمة الحافظة الموحدة للنسخ والقص واللصق والعلاقات المعلقة.', behavior: 'تنفذ عمليات clipboard الموجودة في editor-store.', constraints: 'لا تغير قواعد clone/relate أو معرفات البيانات عند تعديل مظهر القائمة.', dependencies: [], relatedIds: ['A114', 'A121', 'A128'], codeReferences: ['copySelection', 'cutSelection', 'requestPasteSelection'] }),
  active({ id: 'A107', kind: 'panel', name: 'Ayah Navigator', featureId: 'A001', parentId: 'A020', route: '/editor', component: 'AyahNavigator', sourceFile: 'src/components/editor/AyahNavigator.tsx', description: 'مستعرض السورة والآية والبحث في نص المصحف.', behavior: 'ينقل المستند المفتوح إلى الموضع المختار أو نتيجة البحث.', constraints: 'لا يغيّر محتوى المستند عند التنقل.', dependencies: [], relatedIds: ['A108', 'A109', 'A110', 'A111'], codeReferences: ['onNavigate', 'searchQuran'] }),
  active({ id: 'A108', kind: 'select', name: 'Surah Selector', featureId: 'A001', parentId: 'A107', route: '/editor', component: 'AyahNavigator', sourceFile: 'src/components/editor/AyahNavigator.tsx', description: 'قائمة اختيار السورة في محرر الآية.', behavior: 'ينتقل إلى الآية الأولى من السورة المختارة.', constraints: 'المعنى مرتبط باختيار سورة لا بنص الخيار الحالي.', dependencies: [], relatedIds: ['A109'], codeReferences: ['makeAyahKey'] }),
  active({ id: 'A109', kind: 'select', name: 'Ayah Selector', featureId: 'A001', parentId: 'A107', route: '/editor', component: 'AyahNavigator', sourceFile: 'src/components/editor/AyahNavigator.tsx', description: 'قائمة اختيار رقم الآية.', behavior: 'ينتقل إلى الآية المختارة ضمن السورة الحالية.', constraints: 'لا تعيد تهيئة بيانات آية أخرى غير المحددة.', dependencies: [], relatedIds: ['A108'], codeReferences: ['makeAyahKey', 'onNavigate'] }),
  active({ id: 'A110', kind: 'input', name: 'Quran Text Search Input', featureId: 'A001', parentId: 'A107', route: '/editor', component: 'AyahNavigator', sourceFile: 'src/components/editor/AyahNavigator.tsx', description: 'حقل بحث نص المصحف للانتقال إلى آية مطابقة.', behavior: 'يعرض اقتراحات بحث ثم يفتح الآية المختارة.', constraints: 'البحث تنقل فقط، ولا يعدل نص المصحف.', dependencies: [], relatedIds: ['A107', 'A111'], codeReferences: ['searchQuran'] }),
  active({ id: 'A111', kind: 'panel', name: 'Tashjeer Canvas', featureId: 'A001', parentId: 'A100', route: '/editor', component: 'TashjeerCanvas', sourceFile: 'src/components/editor/TashjeerCanvas.tsx', description: 'لوحة SVG لنص الآية وخطوط التشجير والتحديد.', behavior: 'تعرض ناتج التشجير وتدعم اختيار الكلمات والحروف والأسطر.', constraints: 'الرسم مشتق من المستند والمحرك؛ لا تجعل تغيير الواجهة يعدل منطق التوليد.', dependencies: ['A113', 'A114'], relatedIds: ['A112', 'A130'], codeReferences: ['useAyahTashjeer', 'TashjeerFigure'] }),
  active({ id: 'A112', kind: 'panel', name: 'Selection Breadcrumb', featureId: 'A001', parentId: 'A100', route: '/editor', component: 'SelectionBreadcrumb', sourceFile: 'src/components/editor/SelectionBreadcrumb.tsx', description: 'سلسلة سياق العنصر المحدد عبر الآية والسطر والاختلاف والوجه.', behavior: 'تعرض التحديد الموحد الحالي وتتيح الانتقال بين سياقه.', constraints: 'قراءة من selection-store؛ لا تستحدث selection state محلية.', dependencies: [], relatedIds: ['A129', 'A130'], codeReferences: ['useEditorStore', 'selection-store'] }),
  active({ id: 'A113', kind: 'panel', name: 'Editor Properties Panel', featureId: 'A001', parentId: 'A020', route: '/editor', component: 'PropertiesPanel', sourceFile: 'src/components/editor/PropertiesPanel.tsx', description: 'تفاصيل المستند والاختلاف والوجه، الترتيب وإعدادات القراءة.', behavior: 'يحرر خصائص الكيان المحدد عبر editor-store والمكونات الفرعية.', constraints: 'كل تغيير إلى البيانات يجب أن يبقى محكوما بسلوك العمليات الحالية والتراجع.', dependencies: ['A129', 'A123', 'A128'], relatedIds: ['A111', 'A114'], codeReferences: ['useEditorStore', 'setDocumentStatus'] }),
  active({ id: 'A114', kind: 'panel', name: 'Differences and Variants Panel', featureId: 'A001', parentId: 'A020', route: '/editor', component: 'VariantsPanel', sourceFile: 'src/components/editor/VariantsPanel.tsx', description: 'لوحة اختلافات الآية والأوجه والقواعد العامة وأدوات الإنشاء.', behavior: 'تحدد الاختلافات والأوجه وتتيح إنشاءها أو تحريرها أو حذفها وتعميمها.', constraints: 'لا تستبدل اختلافا قائما عند إنشاء اختلاف ثانٍ؛ تبقى العلاقات ونموذج البيانات كما هما.', dependencies: ['A117', 'A118', 'A119', 'A121', 'A421'], relatedIds: ['A115', 'A116', 'A333', 'A140', 'A143'], codeReferences: ['requestDeleteItems', 'setMultiSelection', 'applySmartCreateBatch'] }),
  active({ id: 'A115', kind: 'button', name: 'Open Rules Index Button', featureId: 'A001', parentId: 'A114', route: '/editor', component: 'VariantsPanel', sourceFile: 'src/components/editor/VariantsPanel.tsx', description: 'يفتح فهرس القواعد والاختلافات الكامل داخل المحرر.', behavior: 'يفتح RulesIndexDialog دون تغيير سجل البيانات.', constraints: 'فتح الفهرس لا يغير تحديد المستخدم إلا عبر إجراء صريح.', dependencies: ['A140'], relatedIds: ['A114'], codeReferences: ['setShowRulesIndex'] }),
  active({ id: 'A116', kind: 'button', name: 'Open Smart Create Button', featureId: 'A001', parentId: 'A114', route: '/editor', component: 'VariantsPanel', sourceFile: 'src/components/editor/VariantsPanel.tsx', description: 'يفتح معالج الإنشاء الذكي من لوحة الاختلافات.', behavior: 'يعرض المعالج الموحد ويبدأ من التحديد الحالي أو يسمح بالتحديد داخل المعالج.', constraints: 'زر الفتح لا ينشئ اختلافا بمفرده.', dependencies: ['A421'], relatedIds: ['A102', 'A114'], codeReferences: ['setShowSmartWizard'] }),
  active({ id: 'A117', kind: 'input', name: 'Differences Search Input', featureId: 'A001', parentId: 'A114', route: '/editor', component: 'VariantsPanel', sourceFile: 'src/components/editor/VariantsPanel.tsx', description: 'بحث فوري في اختلافات الآية المعروضة.', behavior: 'يصفّي قائمة الاختلافات بحسب نصها وفئتها وحالتها ومصدرها.', constraints: 'التصفية لا تحذف ولا تعدل بيانات.', dependencies: ['A118'], relatedIds: ['A119'], codeReferences: ['listSearch', 'visibleVariants'] }),
  active({ id: 'A118', kind: 'list', name: 'Differences List', featureId: 'A001', parentId: 'A114', route: '/editor', component: 'VariantsPanel', sourceFile: 'src/components/editor/VariantsPanel.tsx', description: 'قائمة الاختلافات والوجوه للآية المفتوحة.', behavior: 'تدعم التحديد الموحد والمتعدد والتمرير الافتراضي.', constraints: 'ترتيب العرض لا يعرّف هوية الاختلافات ولا يغير رتبتها المحفوظة.', dependencies: ['A117'], relatedIds: ['A119', 'A121', 'A333'], codeReferences: ['ScrollableList', 'useEditorStore'] }),
  active({ id: 'A119', kind: 'toolbar', name: 'Difference Multi-selection Actions', featureId: 'A001', parentId: 'A114', route: '/editor', component: 'VariantsPanel', sourceFile: 'src/components/editor/VariantsPanel.tsx', description: 'شريط عمليات التحديد المتعدد للاختلافات.', behavior: 'يعرض عدد المحدد ويوفر حذف المحدد والنسخ وإلغاء التحديد.', constraints: 'الحذف الكمي يبقى مؤكدا وقابلا للتراجع كعملية واحدة.', dependencies: ['A333'], relatedIds: ['A118', 'A106'], codeReferences: ['setMultiSelection', 'requestDeleteItems'] }),
  active({ id: 'A333', kind: 'button', name: 'Delete Selected Differences Button', featureId: 'A001', parentId: 'A119', route: '/editor', component: 'VariantsPanel', sourceFile: 'src/components/editor/VariantsPanel.tsx', description: 'يحذف الاختلافات المحددة من قائمة الآية بعد عرض التأكيد الكمي.', behavior: 'يستدعي requestDeleteItems بنوع DIFFERENCE ومعرفات التحديد الحالية.', constraints: 'لا يحذف أوجها أو علاقات أو اختلافات أخرى غير مشمولة بالمعرفات؛ التأكيد والتراجع الحاليان محفوظان.', dependencies: ['A119', 'A327'], relatedIds: ['A118', 'A114'], codeReferences: ['requestDeleteItems', 'editor-store.deleteVariants'] }),
  active({ id: 'A121', kind: 'list', name: 'Variant Faces List', featureId: 'A001', parentId: 'A118', route: '/editor', component: 'VariantsPanel', sourceFile: 'src/components/editor/VariantsPanel.tsx', description: 'قائمة أوجه الاختلاف المحدد.', behavior: 'تدعم اختيار الوجه وتحديد عدة أوجه للعمليات الجماعية.', constraints: 'الوجه الأساسي/المصحف ليس وجها قابلا للحذف الجماعي.', dependencies: ['A122'], relatedIds: ['A106', 'A333'], codeReferences: ['alternative.isBase', 'selectedAlternativeId'] }),
  active({ id: 'A122', kind: 'checkbox', name: 'Bulk Face Selection Checkbox', featureId: 'A001', parentId: 'A121', route: '/editor', component: 'VariantsPanel', sourceFile: 'src/components/editor/VariantsPanel.tsx', description: 'مربع تحديد الوجه لعمليات الأوجه الجماعية.', behavior: 'يضيف/يزيل معرف الوجه إلى التحديد المتعدد.', constraints: 'لكل وجه نسخة؛ استخدم alternative.id كـ data-ui-instance. لا يحذف الوجه بمجرد وضع العلامة؛ التنفيذ يحتاج عملية الحذف المؤكدة.', dependencies: [], relatedIds: ['A121'], codeReferences: ['setMultiSelection', 'FACE', 'alternative.id'] }),
  active({ id: 'A123', kind: 'list', name: 'Line Order Editor', featureId: 'A001', parentId: 'A128', route: '/editor', component: 'LineOrderEditor', sourceFile: 'src/components/editor/LineOrderEditor.tsx', description: 'قائمة ترتيب أسطر التشجير بالسحب والتأكيد.', behavior: 'تتيح النقل والدمج والرتبة الرقمية ضمن أوامر المحرر.', constraints: 'لا يتغير الترتيب قبل التأكيد؛ IDs والروابط محفوظة خلال النقل.', dependencies: ['A124', 'A125', 'A126', 'A127'], relatedIds: ['A111', 'A129'], codeReferences: ['moveLineToIndex', 'planLineInsertion', 'confirmAction'] }),
  active({ id: 'A124', kind: 'list-item', name: 'Line Reorder Row', featureId: 'A001', parentId: 'A123', route: '/editor', component: 'LineOrderEditor', sourceFile: 'src/components/editor/LineOrderEditor.tsx', description: 'صف سطر التشجير القابل للسحب أو التحديد بلوحة المفاتيح.', behavior: 'يدعم long press والسحب وShift/Ctrl selection وAlt+Arrow.', constraints: 'معرف السطر مصدر الهوية؛ index وموضع العرض ليسا معرفا ثابتا.', dependencies: ['A125', 'A126', 'A127'], relatedIds: ['A123'], codeReferences: ['data-order-line-id', 'onPointerDown', 'moveLineToIndex'] }),
  active({ id: 'A125', kind: 'drag-handle', name: 'Line Merge Handle', featureId: 'A001', parentId: 'A124', route: '/editor', component: 'LineOrderEditor', sourceFile: 'src/components/editor/LineOrderEditor.tsx', description: 'مقبض دمج سطر مع سطر آخر.', behavior: 'يبدأ إيماءة الدمج ويمررها عبر بوابة السياسة والتأكيد الموجودين.', constraints: 'لا يدمج مباشرة عند pointer down؛ الإلغاء لا يغير المستند.', dependencies: ['A123'], relatedIds: ['A124'], codeReferences: ['down', 'MERGE', 'confirmAction'] }),
  active({ id: 'A126', kind: 'input', name: 'Line Rank Input', featureId: 'A001', parentId: 'A124', route: '/editor', component: 'LineOrderEditor', sourceFile: 'src/components/editor/LineOrderEditor.tsx', description: 'حقل الرتبة الصريحة لسطر التشجير.', behavior: 'يطلب نقل السطر إلى الرتبة المدخلة بعد التحقق والتأكيد.', constraints: 'القيمة خارج النطاق أو غير الصحيحة لا تطبق؛ الرتبة لا تستبدل هوية السطر.', dependencies: ['A123'], relatedIds: ['A124'], codeReferences: ['RankInput', 'confirmOrder'] }),
  active({ id: 'A127', kind: 'control', name: 'Line Move Controls', featureId: 'A001', parentId: 'A124', route: '/editor', component: 'LineOrderEditor', sourceFile: 'src/components/editor/LineOrderEditor.tsx', description: 'أزرار نقل السطر لأعلى أو لأسفل.', behavior: 'تطلب نقل السطر بموضع واحد عبر إجراء الترتيب المؤكد.', constraints: 'تبقى معطلة عند حدود القائمة ولا تغير العلاقات أو معرف السطر.', dependencies: ['A123'], relatedIds: ['A124', 'A126'], codeReferences: ['confirmOrder', 'moveLineToIndex'] }),
  active({ id: 'A128', kind: 'panel', name: 'Relations Panel', featureId: 'A001', parentId: 'A113', route: '/editor', component: 'RelationsPanel', sourceFile: 'src/components/editor/RelationsPanel.tsx', description: 'إدارة علاقات الوجوه والاختلافات والأسطر.', behavior: 'يعرض العلاقات ويطلب إنشاء/فك روابط عبر API المخزن وقرار السياسة.', constraints: 'لا تنشئ علاقة أو تصحيحا يدويا عند تعديل presentation فقط.', dependencies: ['A327'], relatedIds: ['A129', 'A111'], codeReferences: ['requestAddLink', 'manualDifferenceRelationsOf', 'resolveLocusRelation'] }),
  active({ id: 'A129', kind: 'panel', name: 'Selected Element Details Panel', featureId: 'A001', parentId: 'A113', route: '/editor', component: 'SelectionDetailsPanel', sourceFile: 'src/components/editor/SelectionDetailsPanel.tsx', description: 'تفاصيل العنصر المحدد وسياقه وأوامر النسخ والتحديد.', behavior: 'يعرض الحالة الموحدة ويتيح إجراءات مشتركة للعنصر النشط.', constraints: 'لا ينشئ selection state محلية؛ يقرأ المصدر الموحد.', dependencies: [], relatedIds: ['A112', 'A128', 'A130'], codeReferences: ['useEditorStore', 'selection-store'] }),
  active({ id: 'A130', kind: 'menu', name: 'Selection Context Menu', featureId: 'A001', parentId: 'A111', route: '/editor', component: 'SelectionContextMenu', sourceFile: 'src/components/editor/SelectionContextMenu.tsx', description: 'قائمة سياقية للأوامر المتاحة على العنصر النشط.', behavior: 'تدير copy/cut/paste/delete/edit ونحوها عبر إجراءات المحرر القائمة.', constraints: 'تظهر الأوامر بحسب نوع التحديد وصلاحيتها؛ لا تغير ترتيب أو بيانات غير محددة.', dependencies: ['A129', 'A106'], relatedIds: ['A111', 'A128'], codeReferences: ['SelectionCommand', 'deleteActive'] }),
  active({ id: 'A131', kind: 'dialog', name: 'Keyboard Shortcuts Dialog', featureId: 'A001', parentId: 'A020', route: '/editor', component: 'ShortcutsDialog', sourceFile: 'src/components/editor/ShortcutsDialog.tsx', description: 'نافذة اختصارات المحرر.', behavior: 'تعرض الاختصارات وتغلق بطلب المستخدم.', constraints: 'نافذة معلوماتية لا تغير المستند.', dependencies: [], relatedIds: ['A101'], codeReferences: ['onClose'] }),
  active({ id: 'A132', kind: 'button', name: 'Focus Mode Toggle', featureId: 'A001', parentId: 'A020', route: '/editor', component: 'EditorPage', sourceFile: 'src/app/(dashboard)/editor/page.tsx', description: 'زر إخفاء/إظهار الأشرطة واللوحات في وضع التركيز.', behavior: 'يبدل focusMode ويكشف الحواف عند مرور المؤشر.', constraints: 'لا يغير محتوى المستند ولا إعدادات المحرك.', dependencies: [], relatedIds: ['A101', 'A107', 'A113', 'A114'], codeReferences: ['focusMode', 'setFocusMode'] }),
  active({ id: 'A133', kind: 'section', name: 'Editor Status Bar', featureId: 'A001', parentId: 'A020', route: '/editor', component: 'StatusBar', sourceFile: 'src/app/(dashboard)/editor/page.tsx', description: 'شريط موضع الآية والأداة وحالة الحفظ.', behavior: 'يعرض الحالة الحالية للمستند دون تنفيذ تعديل.', constraints: 'معلومات مشتقة؛ لا تصبح مصدرا إضافيا للحقيقة.', dependencies: [], relatedIds: ['A101', 'A107'], codeReferences: ['formatAyahRef', 'isDirty'] }),
  active({ id: 'A134', kind: 'input', name: 'Document Import File Input', featureId: 'A001', parentId: 'A020', route: '/editor', component: 'EditorPage', sourceFile: 'src/app/(dashboard)/editor/page.tsx', description: 'منتقي ملف JSON المخفي لاستيراد مستندات التشجير.', behavior: 'يمرر الملف إلى importDocuments ثم يفتح أول مستند مستورد عند توافره.', constraints: 'يقبل application/json فقط؛ لا تحذف معالجة أخطاء الاستيراد.', dependencies: [], relatedIds: ['A135', 'A136'], codeReferences: ['importDocuments', 'describeImportResult'] }),
  active({ id: 'A135', kind: 'button', name: 'Export Editor Document Button', featureId: 'A001', parentId: 'A101', route: '/editor', component: 'EditorToolbar', sourceFile: 'src/components/editor/EditorToolbar.tsx', description: 'يصدر مستند الآية إلى ملف JSON.', behavior: 'ينفذ callback التصدير الحالي للمستند المفتوح.', constraints: 'التصدير يبقى حتميا وفقا لتنسيق المستند ولا يغير الحالة.', dependencies: [], relatedIds: ['A134'], codeReferences: ['exportDocument', 'onExport'] }),
  active({ id: 'A136', kind: 'button', name: 'Save Editor Document Button', featureId: 'A001', parentId: 'A101', route: '/editor', component: 'EditorToolbar', sourceFile: 'src/components/editor/EditorToolbar.tsx', description: 'يحفظ مستند المحرر المفتوح.', behavior: 'يستدعي save من editor-store ويعرض حالة dirty الحالية.', constraints: 'لا تغيّر صيغة التخزين أو حدود المستند من تعديل زر فقط.', dependencies: [], relatedIds: ['A105', 'A134'], codeReferences: ['save', 'isDirty'] }),
  active({ id: 'A137', kind: 'select', name: 'Canvas Zoom Preset Selector', featureId: 'A001', parentId: 'A101', route: '/editor', component: 'EditorToolbar', sourceFile: 'src/components/editor/EditorToolbar.tsx', description: 'اختيار مستوى تكبير لوحة التشجير.', behavior: 'يعيّن zoom لأحد المستويات المتاحة.', constraints: 'تحكم عرض فقط؛ لا يؤثر على نموذج البيانات.', dependencies: [], relatedIds: ['A111'], codeReferences: ['ZOOM_PRESETS', 'setZoom'] }),
  active({ id: 'A139', kind: 'panel', name: 'Recitation and Layout Controls', featureId: 'A001', parentId: 'A113', route: '/editor', component: 'RecitationControls', sourceFile: 'src/components/editor/RecitationControls.tsx', description: 'مجموعات تحكم قراءة وترتيب/تكوين التشجير المرتبطة بلوحة الخصائص.', behavior: 'تعدل خيارات القراءة أو يدوية الترتيب عبر المخزن الحالي.', constraints: 'تغييرات ترتيب الأسطر تظل صريحة وقابلة للتراجع.', dependencies: ['A123'], relatedIds: ['A111', 'A113'], codeReferences: ['useEditorStore', 'TashjeerOrderControls'] }),
  active({ id: 'A140', kind: 'dialog', name: 'Rules and Differences Index Dialog', featureId: 'A001', parentId: 'A114', route: '/editor', component: 'RulesIndexDialog', sourceFile: 'src/components/editor/RulesIndexDialog.tsx', description: 'فهرس قواعد المصحف والاختلافات العامة والمحلية.', behavior: 'يبحث ويصفّي ويتيح مراجعة مواضع القاعدة وبياناتها.', constraints: 'قراءة الفهرس لا تنشئ تغييرا قبل إجراء تحرير صريح.', dependencies: [], relatedIds: ['A115', 'A141', 'A143', 'A144'], codeReferences: ['readIndexRows', 'RuleOccurrenceReview', 'GlobalRuleMetaEditor'] }),
  active({ id: 'A141', kind: 'dialog', name: 'Rule Occurrence Review Dialog', featureId: 'A001', parentId: 'A140', route: '/editor', component: 'RuleOccurrenceReview', sourceFile: 'src/components/editor/RuleOccurrenceReview.tsx', description: 'مراجعة مواضع القاعدة العامة في المصحف.', behavior: 'يعرض المطابقات ويسمح بمراجعة موضعية وتسجيل تجاوزات محلية.', constraints: 'الموضع المستثنى أو المعدل لا يغير القاعدة الأم.', dependencies: ['A327'], relatedIds: ['A140', 'A144'], codeReferences: ['useRuleOccurrences', 'occurrenceOverrides'] }),
  active({ id: 'A142', kind: 'dialog', name: 'Global Rule Builder Dialog', featureId: 'A001', parentId: 'A114', route: '/editor', component: 'GlobalRuleBuilder', sourceFile: 'src/components/editor/GlobalRuleBuilder.tsx', description: 'إنشاء قاعدة عامة نمطية أو نحوية.', behavior: 'يبني قاعدة معاينة ثم يحفظها في مخزن القواعد العامة عبر المسار الحالي.', constraints: 'لا تنشئ نسخا مشتقة داخل مستندات الآيات؛ المعاينة لا تطبق التغيير.', dependencies: ['A327'], relatedIds: ['A114', 'A140'], codeReferences: ['saveGlobalRule', 'findGlobalRuleMatches'] }),
  active({ id: 'A143', kind: 'dialog', name: 'Global Rule Metadata Editor', featureId: 'A001', parentId: 'A140', route: '/editor', component: 'GlobalRuleMetaEditor', sourceFile: 'src/components/editor/GlobalRuleMetaEditor.tsx', description: 'تعديل بيانات القاعدة العامة ونطاقها ودرجاتها.', behavior: 'يحفظ تعديل قاعدة محددة مع حماية التجاوزات المحلية.', constraints: 'لا يبدل هوية القاعدة لمجرد تغيير عنوانها أو حقولها.', dependencies: ['A327'], relatedIds: ['A140', 'A141'], codeReferences: ['saveGlobalRule', 'pruneStrengthMap'] }),
  active({ id: 'A144', kind: 'dialog', name: 'Local Override Editor', featureId: 'A001', parentId: 'A141', route: '/editor', component: 'LocalOverrideEditor', sourceFile: 'src/components/editor/LocalOverrideEditor.tsx', description: 'تحرير استثناء أو تجاوز محلي لموضع قاعدة عامة.', behavior: 'يحفظ override للموضع وحده.', constraints: 'يظل global rule قائما ولا تتسرب الحقول المحلية إلى المواضع الأخرى.', dependencies: ['A327'], relatedIds: ['A141', 'A143'], codeReferences: ['localOverride', 'rule-occurrences-store'] }),
  active({ id: 'A145', kind: 'control', name: 'Quick Create Template Controls', featureId: 'A001', parentId: 'A114', route: '/editor', component: 'VariantsPanel', sourceFile: 'src/components/editor/VariantsPanel.tsx', description: 'مجموعة القوالب الجاهزة/المحفوظة للإنشاء السريع.', behavior: 'تمرر إعداد القالب إلى مسار smart-create الحالي.', constraints: 'القالب لا يغير قواعد الإنشاء أو عدد عمليات التراجع.', dependencies: ['A421'], relatedIds: ['A116'], codeReferences: ['QUICK_CREATE_TEMPLATES', 'handleQuickCreate'] }),
  active({ id: 'A421', kind: 'dialog', name: 'Smart Create Wizard Dialog', featureId: 'A001', parentId: 'A114', route: '/editor', component: 'SmartCreateWizard', sourceFile: 'src/components/editor/SmartCreateWizard.tsx', description: 'معالج إنشاء موحد متعدد الخطوات للاختلافات والأوجه والنطاق والعلاقات والتعميم.', behavior: 'يبني دفعة ذرية من مدخلات المستخدم ثم يطبقها عبر مسار المخزن القائم.', constraints: 'لا تغير منطق smart-create أو نموذج البيانات في طلب يخص واجهة المعالج فقط؛ كل علاقة/تعميم يحتاج مساره الصريح.', dependencies: ['A116', 'A145'], relatedIds: ['A111', 'A114', 'A142'], codeReferences: ['buildSmartCreateBatch', 'buildSmartCreateMultiTargetBatch', 'applySmartCreateBatch'] }),

  // Engine Studio.
  active({ id: 'A150', kind: 'shell', name: 'Engine Studio Workspace', featureId: 'A002', parentId: 'A021', route: '/studio', component: 'EngineStudioPage', sourceFile: 'src/app/(dashboard)/studio/page.tsx', description: 'مساحة أقسام إعداد سياسات المحرك.', behavior: 'تبدل اللوحة النشطة داخل الاستوديو مع الاحتفاظ بحالة الملف.', constraints: 'لا يعدل المحرك قبل الإجراء الصريح المناسب.', dependencies: ['A155'], relatedIds: ['A151', 'A158', 'A163', 'A169'], codeReferences: ['useEngineStudioStore'] }),
  active({ id: 'A151', kind: 'section', name: 'Engine Studio Header', featureId: 'A002', parentId: 'A150', route: '/studio', component: 'EngineStudioPage', sourceFile: 'src/app/(dashboard)/studio/page.tsx', description: 'عنوان الملف ومؤشر التعديلات وأوامر إعادة الضبط/المراجعة/الحفظ.', behavior: 'يعرض حالة الملف ويشغل الأوامر العامة للاستوديو.', constraints: 'الحفظ مشروط بـ dirty؛ إعادة الضبط تمر عبر التأكيد الحالي.', dependencies: ['A152', 'A153', 'A154'], relatedIds: ['A169'], codeReferences: ['dirty', 'persist', 'resetToDefault'] }),
  active({ id: 'A152', kind: 'button', name: 'Reset Engine Configuration Button', featureId: 'A002', parentId: 'A151', route: '/studio', component: 'EngineStudioPage', sourceFile: 'src/app/(dashboard)/studio/page.tsx', description: 'يعيد إعداد المحرك إلى سياسات النظام الافتراضية.', behavior: 'يعرض تأكيدا كميا ثم يستدعي resetToDefault.', constraints: 'لا ينفذ إعادة الضبط قبل موافقة المستخدم.', dependencies: [], relatedIds: ['A154', 'A327'], codeReferences: ['resetToDefault', 'confirmAction'] }),
  active({ id: 'A153', kind: 'button', name: 'Review Before Publish Button', featureId: 'A002', parentId: 'A151', route: '/studio', component: 'EngineStudioPage', sourceFile: 'src/app/(dashboard)/studio/page.tsx', description: 'يفتح بوابة مراجعة النشر عند وجود تغييرات.', behavior: 'ينقل إلى قسم النشر والسجل.', constraints: 'لا ينشر أو يحفظ بمفرده.', dependencies: ['A169'], relatedIds: ['A154'], codeReferences: ['setSection("publish")'] }),
  active({ id: 'A154', kind: 'button', name: 'Save Engine Configuration Button', featureId: 'A002', parentId: 'A151', route: '/studio', component: 'EngineStudioPage', sourceFile: 'src/app/(dashboard)/studio/page.tsx', description: 'يحفظ إعداد المحرك الحالي.', behavior: 'يستدعي persist عند وجود تغييرات غير محفوظة.', constraints: 'لا تغير شكل ملف التصدير أو سياسة resolver من تعديل واجهة الزر.', dependencies: [], relatedIds: ['A151', 'A169'], codeReferences: ['persist', 'engine-config-store'] }),
  active({ id: 'A155', kind: 'navigation', name: 'Engine Studio Sections Navigation', featureId: 'A002', parentId: 'A150', route: '/studio', component: 'EngineStudioPage', sourceFile: 'src/app/(dashboard)/studio/page.tsx', description: 'قائمة أقسام الاستوديو الاثني عشر.', behavior: 'تحدد لوحة العمل الحالية وتدعم deep links المدعومة.', constraints: 'معرفات الأقسام الداخلية ليست UI IDs ولا تتغير هوية القسم بسبب إعادة ترتيب عرضه.', dependencies: [], relatedIds: ['A156', 'A157', 'A158', 'A163', 'A164', 'A165', 'A166', 'A167', 'A168', 'A169', 'A170', 'A171'], codeReferences: ['SECTIONS', 'readDeepLink'] }),
  active({ id: 'A156', kind: 'panel', name: 'Engine Studio Dashboard', featureId: 'A002', parentId: 'A150', route: '/studio', component: 'Dashboard', sourceFile: 'src/components/studio/Dashboard.tsx', description: 'لوحة ملخص إعداد المحرك وحالة التدقيق.', behavior: 'تعرض أعداد القواعد ومشكلات الفحص للقراءة.', constraints: 'لا تحفظ أو تعدل ملف المحرك.', dependencies: [], relatedIds: ['A155'], codeReferences: ['auditProfile'] }),
  active({ id: 'A157', kind: 'panel', name: 'Recitation Rule Catalog Panel', featureId: 'A002', parentId: 'A150', route: '/studio', component: 'RecitationRuleCatalogPanel', sourceFile: 'src/components/studio/RecitationRuleCatalogPanel.tsx', description: 'مكتبة قواعد قرائية/معجمية قابلة للإدارة.', behavior: 'تعرض القواعد والمرشحات ونماذج التحرير.', constraints: 'بيانات المكتبة لا تعني تفعيل قاعدة قرار إلا عبر المسار الموثق.', dependencies: [], relatedIds: ['A155'], codeReferences: ['recitation-rule-catalog.ts'] }),
  active({ id: 'A158', kind: 'panel', name: 'Engine Rule Explorer', featureId: 'A002', parentId: 'A150', route: '/studio', component: 'RuleExplorer', sourceFile: 'src/components/studio/RuleExplorer.tsx', description: 'قائمة استكشاف قواعد المحرك مع مرشحات.', behavior: 'تبحث وتصفّي وترتب القواعد وتحدد القاعدة المطلوب تحريرها.', constraints: 'المرشحات تغيّر العرض فقط ولا تحذف قواعد.', dependencies: ['A159', 'A160'], relatedIds: ['A161', 'A162'], codeReferences: ['onSelect', 'onCreate'] }),
  active({ id: 'A159', kind: 'input', name: 'Engine Rule Search Input', featureId: 'A002', parentId: 'A158', route: '/studio', component: 'RuleExplorer', sourceFile: 'src/components/studio/RuleExplorer.tsx', description: 'حقل بحث قواعد المحرك.', behavior: 'يصفّي القائمة بالاسم أو محتوى القاعدة.', constraints: 'البحث لا يغير ملف المحرك.', dependencies: [], relatedIds: ['A158'], codeReferences: ['query', 'setQuery'] }),
  active({ id: 'A160', kind: 'button', name: 'Create Engine Rule Button', featureId: 'A002', parentId: 'A158', route: '/studio', component: 'RuleExplorer', sourceFile: 'src/components/studio/RuleExplorer.tsx', description: 'يبدأ مسودة قاعدة محرك جديدة.', behavior: 'ينقل الصفحة إلى وضع منشئ قاعدة فارغ.', constraints: 'لا يضيف القاعدة إلى الإعداد قبل الحفظ الصريح.', dependencies: ['A161'], relatedIds: ['A158'], codeReferences: ['onCreate', 'setCreatingNew'] }),
  active({ id: 'A161', kind: 'form', name: 'Engine Rule Builder Form', featureId: 'A002', parentId: 'A150', route: '/studio', component: 'RuleBuilder', sourceFile: 'src/components/studio/RuleBuilder.tsx', description: 'نموذج إنشاء أو تحرير قاعدة محرك.', behavior: 'يتحقق من الحقول ويسلم القاعدة إلى onSave أو يلغي المسودة.', constraints: 'الشروط والإجراءات والسياسة لا تتغير بمجرد إعادة ترتيب عناصر النموذج.', dependencies: [], relatedIds: ['A158', 'A160'], codeReferences: ['onSave', 'EngineRule'] }),
  active({ id: 'A162', kind: 'panel', name: 'Selected Engine Rule Actions', featureId: 'A002', parentId: 'A150', route: '/studio', component: 'SelectedRuleActions', sourceFile: 'src/app/(dashboard)/studio/page.tsx', description: 'إجراءات سريعة على القاعدة المحددة: أولوية، حالة، حذف.', behavior: 'يستدعي عمليات store المرتبطة بالقاعدة المحددة.', constraints: 'الحذف يظل مؤكدا ويأخذ الاعتماديات الحالية في الحسبان.', dependencies: ['A327'], relatedIds: ['A158', 'A161'], codeReferences: ['setRulePriorityAction', 'setRuleStatusAction', 'removeRule'] }),
  active({ id: 'A163', kind: 'panel', name: 'Merge Matrix Panel', featureId: 'A002', parentId: 'A150', route: '/studio', component: 'MergeMatrixPanel', sourceFile: 'src/components/studio/MergeMatrixPanel.tsx', description: 'مصفوفة قواعد الدمج والعلاقات بين الأنواع.', behavior: 'تتيح إضافة/تعديل/حذف سياسات الدمج والعلاقة.', constraints: 'القرار الفعلي يظل عبر Decision Resolver الموحد.', dependencies: [], relatedIds: ['A164', 'A165'], codeReferences: ['onAdd', 'onUpdate', 'onRemove'] }),
  active({ id: 'A164', kind: 'panel', name: 'Priority Pipeline Panel', featureId: 'A002', parentId: 'A150', route: '/studio', component: 'PriorityPipeline', sourceFile: 'src/components/studio/PriorityPipeline.tsx', description: 'ترتيب مراحل التنفيذ ومجموعات الأولوية.', behavior: 'يدير ترتيب مراحل التنفيذ وسياسة حل التعارض والأولويات.', constraints: 'تغيير ترتيب التنفيذ يمر بتقدير أثر وتأكيد.', dependencies: ['A327'], relatedIds: ['A162', 'A165'], codeReferences: ['executionOrderImpact', 'handleExecutionOrderChange'] }),
  active({ id: 'A165', kind: 'panel', name: 'Why and Decision Trace Playground', featureId: 'A002', parentId: 'A150', route: '/studio', component: 'WhyTracePlayground', sourceFile: 'src/components/studio/WhyTracePlayground.tsx', description: 'محاكاة تفسير قرار الدمج وأثر القواعد.', behavior: 'يعرض القرار والـ trace لمدخلات تجريبية.', constraints: 'المحاكاة لا تحفظ ملف المحرك.', dependencies: [], relatedIds: ['A163', 'A164'], codeReferences: ['resolveDifference', 'trace'] }),
  active({ id: 'A166', kind: 'panel', name: 'Engine Rule Tests Panel', featureId: 'A002', parentId: 'A150', route: '/studio', component: 'RuleTestsPanel', sourceFile: 'src/components/studio/RuleTestsPanel.tsx', description: 'تشغيل وعرض اختبارات قواعد ملف المحرك.', behavior: 'يشغل runProfileTests على الإعداد المعروض.', constraints: 'نتائج الاختبار تشخيصية ولا تعدل الإعداد.', dependencies: [], relatedIds: ['A164', 'A168'], codeReferences: ['runProfileTests'] }),
  active({ id: 'A167', kind: 'panel', name: 'Candidate Rules Panel', featureId: 'A002', parentId: 'A150', route: '/studio', component: 'CandidateRulesPanel', sourceFile: 'src/components/studio/CandidateRulesPanel.tsx', description: 'اقتراح قاعدة مرشحة من تصحيح موثق.', behavior: 'ينشئ draft candidate ويتيح تبنيها صراحة.', constraints: 'لا تتحول القاعدة إلى فاعلة تلقائيا.', dependencies: [], relatedIds: ['A161', 'A168'], codeReferences: ['proposeCandidateRule', 'onAdopt'] }),
  active({ id: 'A168', kind: 'panel', name: 'Engine Profile Compare Panel', featureId: 'A002', parentId: 'A150', route: '/studio', component: 'ProfileComparePanel', sourceFile: 'src/components/studio/ProfileComparePanel.tsx', description: 'مقارنة الملف الحالي بملف النظام الافتراضي.', behavior: 'يعرض الفروقات والتصنيف وسلامة الاعتماد.', constraints: 'لا يعدل الملفات ولا يقرر اعتمادا تلقائيا.', dependencies: [], relatedIds: ['A166', 'A169'], codeReferences: ['compareProfiles', 'isSafeToAdopt'] }),
  active({ id: 'A169', kind: 'panel', name: 'Publish Gate and Engine History Panel', featureId: 'A002', parentId: 'A150', route: '/studio', component: 'PublishHistoryPanel', sourceFile: 'src/components/studio/PublishHistoryPanel.tsx', description: 'بوابة مراجعة التغييرات والسجل والاسترجاع.', behavior: 'يعرض dry-run ونسخ الإعداد ويسمح بالنشر/الإلغاء/الاسترجاع المؤكد.', constraints: 'الاسترجاع لا يتم دون تأكيد واضح؛ يحافظ على سجل الإصدارات.', dependencies: ['A327'], relatedIds: ['A153', 'A154', 'A168'], codeReferences: ['diffEngineConfigs', 'onPublish', 'onRollback'] }),
  active({ id: 'A170', kind: 'panel', name: 'Engine Export Import Panel', featureId: 'A002', parentId: 'A150', route: '/studio', component: 'ExportImportPanel', sourceFile: 'src/components/studio/ExportImportPanel.tsx', description: 'تصدير واستيراد ملف إعداد المحرك مع معاينة التحقق.', behavior: 'ينشئ JSON حتميا ويعاين الاستيراد قبل التطبيق.', constraints: 'لا تطبق الاستيراد قبل المعاينة الصالحة والإجراء الصريح.', dependencies: [], relatedIds: ['A154', 'A169'], codeReferences: ['onExport', 'onPreviewImport', 'onImport'] }),
  active({ id: 'A171', kind: 'panel', name: 'Engine Behavior Settings Panel', featureId: 'A002', parentId: 'A150', route: '/studio', component: 'EngineSettingsPanel', sourceFile: 'src/components/studio/EngineSettingsPanel.tsx', description: 'خيارات العرض والترتيب لتكوين محرك التشجير.', behavior: 'يعدل إعداداته محليا ويحفظها بإجراء صريح.', constraints: 'هو مصدر إعدادات العرض المعتمد؛ لا تنشئ نسخة ثانية في admin.', dependencies: [], relatedIds: ['A154'], codeReferences: ['saveEngineSettings', 'resetEngineSettings'] }),

  // Quran reader.
  active({ id: 'A180', kind: 'input', name: 'Surah Search Input', featureId: 'A003', parentId: 'A022', route: '/quran', component: 'QuranPage', sourceFile: 'src/app/(dashboard)/quran/page.tsx', description: 'بحث في أسماء السور.', behavior: 'يصفّي فهرس السور دون تغيير السورة الحالية حتى الاختيار.', constraints: 'لا يغير نص المصحف أو بياناته.', dependencies: ['A181'], relatedIds: ['A181'], codeReferences: ['searchSurahs', 'query'] }),
  active({ id: 'A181', kind: 'list', name: 'Surah Navigation List', featureId: 'A003', parentId: 'A022', route: '/quran', component: 'QuranPage', sourceFile: 'src/app/(dashboard)/quran/page.tsx', description: 'قائمة اختيار السورة.', behavior: 'تحدد السورة النشطة وتحدث محتوى منطقة القراءة.', constraints: 'تسلسل القائمة لا يمثل ID للسورة؛ معرفات البيانات هي المصدر.', dependencies: ['A180'], relatedIds: ['A182'], codeReferences: ['setSurahNumber', 'SURAHS'] }),
  active({ id: 'A182', kind: 'section', name: 'Current Surah Reader', featureId: 'A003', parentId: 'A022', route: '/quran', component: 'QuranPage', sourceFile: 'src/app/(dashboard)/quran/page.tsx', description: 'قسم نص السورة الحالية وآياتها.', behavior: 'يرسم الآيات وربط التشجير المحفوظ/المشتق.', constraints: 'النص للقراءة؛ لا تعدل محتوى المصحف من هذا السطح.', dependencies: ['A183', 'A184', 'A187'], relatedIds: ['A181'], codeReferences: ['getSurahAyahs', 'AyahTashjeerView'] }),
  active({ id: 'A183', kind: 'button', name: 'Toggle Saved Tashjeer Visibility', featureId: 'A003', parentId: 'A182', route: '/quran', component: 'QuranPage', sourceFile: 'src/app/(dashboard)/quran/page.tsx', description: 'زر عرض/إخفاء التشجير أسفل الآيات.', behavior: 'يبدل showTashjeer في واجهة المصحف.', constraints: 'يغير الرؤية فقط ولا يحذف التشجير المحفوظ.', dependencies: [], relatedIds: ['A187'], codeReferences: ['setShowTashjeer'] }),
  active({ id: 'A184', kind: 'list-item', name: 'Quran Ayah Row', featureId: 'A003', parentId: 'A182', route: '/quran', component: 'QuranPage', sourceFile: 'src/app/(dashboard)/quran/page.tsx', description: 'عنصر الآية في قائمة السورة.', behavior: 'يعرض نص الآية ورقمها وروابط أدواتها وبطاقة التشجير عند وجودها.', constraints: 'نسخة قائمة ديناميكية؛ الآية تميزها ayahKey لا index العرض.', dependencies: ['A185', 'A186', 'A187'], relatedIds: ['A182'], codeReferences: ['ayah.key', 'getSurahAyahs'] }),
  active({ id: 'A185', kind: 'navigation', name: 'Open Quran Ayah in Editor Link', featureId: 'A003', parentId: 'A184', route: '/quran', component: 'QuranPage', sourceFile: 'src/app/(dashboard)/quran/page.tsx', description: 'رابط نقل الآية المحددة إلى محرر التشجير.', behavior: 'يفتح /editor مع ayahKey للآية.', constraints: 'لا يفتح آية افتراضية مختلفة ولا يغير المستند من قارئ المصحف.', dependencies: [], relatedIds: ['A020', 'A184'], codeReferences: ['href=/editor?ayah='] }),
  active({ id: 'A186', kind: 'button', name: 'Export Quran Ayah JSON Button', featureId: 'A003', parentId: 'A184', route: '/quran', component: 'QuranPage', sourceFile: 'src/app/(dashboard)/quran/page.tsx', description: 'تصدير ملف JSON للمستند المرتبط بالآية.', behavior: 'ينزل الملف الناتج عن exportAyahDocument.', constraints: 'التصدير لا يحفظ أو يعدل بيانات الآية.', dependencies: [], relatedIds: ['A184'], codeReferences: ['exportAyahJson', 'exportAyahDocument'] }),
  active({ id: 'A187', kind: 'card', name: 'Saved Ayah Tashjeer Card', featureId: 'A003', parentId: 'A184', route: '/quran', component: 'AyahTashjeerView', sourceFile: 'src/components/quran/AyahTashjeerView.tsx', description: 'بطاقة تشجير الآية المحفوظ أو المشتق من قاعدة عامة.', behavior: 'تعرض الحالة والخطوط والبيانات الوصفية وروابط الإجراءات.', constraints: 'تعتمد على نفس hook والمحرك المستخدمين في المحرر؛ لا تنشئ مستندا محفوظا للعرض المشتق.', dependencies: ['A188', 'A189'], relatedIds: ['A111', 'A022'], codeReferences: ['resolveAyahDocument', 'useAyahTashjeer', 'TashjeerFigure'] }),
  active({ id: 'A188', kind: 'button', name: 'Toggle Ayah Tashjeer Card Button', featureId: 'A003', parentId: 'A187', route: '/quran', component: 'AyahTashjeerView', sourceFile: 'src/components/quran/AyahTashjeerView.tsx', description: 'طي أو إظهار رسم التشجير داخل البطاقة.', behavior: 'يبدل open داخل البطاقة.', constraints: 'لا يحذف المستند أو يغير إعداداته.', dependencies: [], relatedIds: ['A187'], codeReferences: ['setOpen'] }),
  active({ id: 'A189', kind: 'navigation', name: 'Open Tashjeer Card in Editor Link', featureId: 'A003', parentId: 'A187', route: '/quran', component: 'AyahTashjeerView', sourceFile: 'src/components/quran/AyahTashjeerView.tsx', description: 'يفتح الآية الحالية مباشرة في المحرر.', behavior: 'ينقل إلى /editor?ayah=<ayahKey>.', constraints: 'تنقل فقط؛ لا يغير حالة المستند.', dependencies: [], relatedIds: ['A020', 'A187'], codeReferences: ['href=/editor?ayahKey'] }),

  // Tracking.
  active({ id: 'A200', kind: 'filter', name: 'Tracking Category Filters', featureId: 'A004', parentId: 'A023', route: '/tracking', component: 'TrackingPage', sourceFile: 'src/app/(dashboard)/tracking/page.tsx', description: 'مرشحات فئة الاختلاف.', behavior: 'تختار فئة واحدة أو الكل وتعيد حساب الصفوف الظاهرة.', constraints: 'تصفية عرض فقط؛ لا تحفظ أو تحذف سجلات.', dependencies: ['A203'], relatedIds: ['A201'], codeReferences: ['setCategory', 'categoriesWithData'] }),
  active({ id: 'A201', kind: 'filter', name: 'Tracking Source Filters', featureId: 'A004', parentId: 'A023', route: '/tracking', component: 'TrackingPage', sourceFile: 'src/app/(dashboard)/tracking/page.tsx', description: 'مرشحات المصدر: الكل، المحرك، المحرر، المعدل يدويا.', behavior: 'تختار مصدر الصفوف الظاهرة.', constraints: 'لا تغير قيم المصدر المسجلة.', dependencies: ['A203'], relatedIds: ['A200'], codeReferences: ['SOURCE_FILTERS', 'setSource'] }),
  active({ id: 'A202', kind: 'panel', name: 'Tracking Summary Cards', featureId: 'A004', parentId: 'A023', route: '/tracking', component: 'TrackingPage', sourceFile: 'src/app/(dashboard)/tracking/page.tsx', description: 'بطاقات أعداد المواضع حسب المصدر والتعديل.', behavior: 'تعرض trackingSummary من الصفوف المحسوبة.', constraints: 'معلومات مشتقة؛ ليست controls لتعديل البيانات.', dependencies: [], relatedIds: ['A203'], codeReferences: ['trackingSummary', 'SummaryCard'] }),
  active({ id: 'A203', kind: 'list', name: 'Tracking Results List', featureId: 'A004', parentId: 'A023', route: '/tracking', component: 'TrackingPage', sourceFile: 'src/app/(dashboard)/tracking/page.tsx', description: 'قائمة عناصر تتبع الاختلافات.', behavior: 'تعرض الصفوف المطابقة للفئة والمصدر المختارين.', constraints: 'هوية الصف مشتقة من row.id وليس ترتيب القائمة.', dependencies: ['A204'], relatedIds: ['A200', 'A201'], codeReferences: ['visible', 'TrackingRowCard'] }),
  active({ id: 'A204', kind: 'list-item', name: 'Tracking Result Card', featureId: 'A004', parentId: 'A203', route: '/tracking', component: 'TrackingRowCard', sourceFile: 'src/app/(dashboard)/tracking/page.tsx', description: 'بطاقة موضع تتبع مع حالة المصدر والفروق وسجل التعديل.', behavior: 'تفتح التفاصيل أو الانتقال إلى المحرر.', constraints: 'بطاقات متعددة؛ استخدم row.id كـ data-ui-instance عند التعامل مع سجل بعينه.', dependencies: ['A205', 'A206', 'A207', 'A208'], relatedIds: ['A023'], codeReferences: ['TrackingRow', 'row.id'] }),
  active({ id: 'A205', kind: 'button', name: 'Toggle Tracking Difference Details', featureId: 'A004', parentId: 'A204', route: '/tracking', component: 'TrackingRowCard', sourceFile: 'src/app/(dashboard)/tracking/page.tsx', description: 'توسيع أو طي سجل الفروق والتصحيح.', behavior: 'يبدل حالة البطاقة الموسعة.', constraints: 'عرض التفاصيل لا يكتب تغييرا على السجل.', dependencies: [], relatedIds: ['A204'], codeReferences: ['onToggle', 'expanded'] }),
  active({ id: 'A206', kind: 'button', name: 'Toggle Decision Trace Details', featureId: 'A004', parentId: 'A204', route: '/tracking', component: 'RowDecisionTrace', sourceFile: 'src/app/(dashboard)/tracking/page.tsx', description: 'إظهار/إخفاء أثر قرار المحرك للصف.', behavior: 'يعرض trace من resolver على الإعداد الحالي.', constraints: 'إعادة الحساب للشرح فقط؛ لا تغير السياسة أو الإعداد.', dependencies: ['A021'], relatedIds: ['A204'], codeReferences: ['resolveDifference', 'result.trace'] }),
  active({ id: 'A207', kind: 'navigation', name: 'Propose Rule from Correction Link', featureId: 'A004', parentId: 'A204', route: '/tracking', component: 'CorrectionTripletView', sourceFile: 'src/app/(dashboard)/tracking/page.tsx', description: 'ينقل التصحيح إلى قسم اقتراح قاعدة في الاستوديو.', behavior: 'يبني deep link مع سياق التصحيح الحالي.', constraints: 'يظل اقتراحا مسودة؛ لا يعتمد قاعدة تلقائيا.', dependencies: ['A021'], relatedIds: ['A204', 'A167'], codeReferences: ['candidateHref', 'CorrectionTripletView'] }),
  active({ id: 'A208', kind: 'navigation', name: 'Open Tracking Row in Editor Link', featureId: 'A004', parentId: 'A204', route: '/tracking', component: 'TrackingRowCard', sourceFile: 'src/app/(dashboard)/tracking/page.tsx', description: 'فتح موضع الصف في محرر الآية.', behavior: 'ينقل إلى المحرر مع ayahKey وvariantId للصف.', constraints: 'تنقل فقط؛ لا تعدل السجل.', dependencies: ['A020'], relatedIds: ['A204'], codeReferences: ['row.ayahKey', 'row.variantId'] }),

  // Cross-document variant index.
  active({ id: 'A220', kind: 'panel', name: 'Variant Index Workspace', featureId: 'A005', parentId: 'A024', route: '/variants', component: 'VariantsIndexPage', sourceFile: 'src/app/(dashboard)/variants/page.tsx', description: 'سطح الفهرس والبحث ونتائج الاختلافات والقواعد العامة.', behavior: 'يجمع مرشحات القائمة وروابط فتح السجل في المحرر.', constraints: 'البحث لا يعدل العناصر.', dependencies: ['A221', 'A222'], relatedIds: ['A223'], codeReferences: ['visible', 'readIndexRows'] }),
  active({ id: 'A221', kind: 'filter', name: 'Variant Index Search and Filters', featureId: 'A005', parentId: 'A220', route: '/variants', component: 'VariantsIndexPage', sourceFile: 'src/app/(dashboard)/variants/page.tsx', description: 'حقل البحث ومرشحات نوع/حالة الفهرس.', behavior: 'تحدد النتائج الظاهرة في الفهرس.', constraints: 'تصفية فقط؛ لا تحفظ تغييرا على قاعدة أو اختلاف.', dependencies: ['A222'], relatedIds: ['A220'], codeReferences: ['query', 'setQuery', 'visible'] }),
  active({ id: 'A222', kind: 'list', name: 'Cross-document Variant Results', featureId: 'A005', parentId: 'A220', route: '/variants', component: 'VariantsIndexPage', sourceFile: 'src/app/(dashboard)/variants/page.tsx', description: 'قائمة الاختلافات والقواعد عبر المستندات.', behavior: 'تعرض السجلات وتوفر روابط التحرير والمراجعة.', constraints: 'ترتيب الصفوف ليس هوية السجل؛ استخدم مفتاح العنصر الحالي.', dependencies: [], relatedIds: ['A221', 'A223'], codeReferences: ['visible.map'] }),
  active({ id: 'A223', kind: 'dialog', name: 'General Rule Editor Dialog', featureId: 'A005', parentId: 'A024', route: '/variants', component: 'GlobalRuleDialog', sourceFile: 'src/app/(dashboard)/variants/page.tsx', description: 'نافذة إنشاء/تحرير قاعدة عامة للمصحف.', behavior: 'تحرير حقول القاعدة وحفظها صراحة.', constraints: 'تعديل القاعدة الأم لا يلغي الحماية والتجاوزات المحلية.', dependencies: [], relatedIds: ['A220', 'A327'], codeReferences: ['save', 'GlobalRuleDialog'] }),

  // Qiraat/readers and review catalog pages.
  active({ id: 'A230', kind: 'input', name: 'Qiraat Search Input', featureId: 'A006', parentId: 'A025', route: '/qiraat', component: 'QiraatPage', sourceFile: 'src/app/(dashboard)/qiraat/page.tsx', description: 'بحث في أسماء القراءات أو بيانات قائمتها.', behavior: 'يصفّي قائمة القراءات المعروضة.', constraints: 'لا يعدل بيانات القراءات.', dependencies: ['A231'], relatedIds: ['A231'], codeReferences: ['search', 'setSearch'] }),
  active({ id: 'A231', kind: 'list', name: 'Qiraat Selection List', featureId: 'A006', parentId: 'A025', route: '/qiraat', component: 'QiraatPage', sourceFile: 'src/app/(dashboard)/qiraat/page.tsx', description: 'قائمة القراءات للاختيار.', behavior: 'تحدد القراءة التي تعرض تفاصيلها.', constraints: 'الترتيب العلمي مأخوذ من البيانات المعتمدة.', dependencies: ['A230', 'A232'], relatedIds: ['A232'], codeReferences: ['qiraat data', 'selectedQiraah'] }),
  active({ id: 'A232', kind: 'panel', name: 'Selected Qiraat Details', featureId: 'A006', parentId: 'A025', route: '/qiraat', component: 'QiraatPage', sourceFile: 'src/app/(dashboard)/qiraat/page.tsx', description: 'بطاقة معلومات القراءة المختارة.', behavior: 'تعرض الإمام والرواة وخصائص البيانات الحالية.', constraints: 'قراءة فقط؛ لا تخلط بينها وبين إدارة الكتالوج في /admin.', dependencies: [], relatedIds: ['A231'], codeReferences: ['selectedQiraah'] }),
  active({ id: 'A240', kind: 'form', name: 'Reader Profile Form', featureId: 'A007', parentId: 'A026', route: '/readers', component: 'ReadersPage', sourceFile: 'src/app/(dashboard)/readers/page.tsx', description: 'نموذج إدخال أو تعديل ملف قارئ.', behavior: 'يتحقق من الحقول ويرسل النموذج وفق الإجراء الحالي.', constraints: 'لا تفترض صلاحية API غير موجودة في التنفيذ الحالي.', dependencies: ['A242', 'A243'], relatedIds: ['A241'], codeReferences: ['handleSubmit'] }),
  active({ id: 'A241', kind: 'list', name: 'Readers Catalog List', featureId: 'A007', parentId: 'A026', route: '/readers', component: 'ReadersPage', sourceFile: 'src/app/(dashboard)/readers/page.tsx', description: 'قائمة ملفات القراء.', behavior: 'تختار سجلا وتعرض إجراءاته الحالية.', constraints: 'المعرف من سجل القارئ لا من موضع القائمة.', dependencies: [], relatedIds: ['A240'], codeReferences: ['readers.map'] }),
  active({ id: 'A242', kind: 'select', name: 'Reader Transmission Selector', featureId: 'A007', parentId: 'A240', route: '/readers', component: 'ReadersPage', sourceFile: 'src/app/(dashboard)/readers/page.tsx', description: 'اختيار صلة القراءة/الرواية في النموذج.', behavior: 'يحدّث قيمة حقل التصنيف المحدد.', constraints: 'القيم تأتي من الكتالوج الحالي.', dependencies: [], relatedIds: ['A240'], codeReferences: ['setFormData'] }),
  active({ id: 'A243', kind: 'button', name: 'Submit Reader Profile Form', featureId: 'A007', parentId: 'A240', route: '/readers', component: 'ReadersPage', sourceFile: 'src/app/(dashboard)/readers/page.tsx', description: 'إرسال نموذج ملف القارئ.', behavior: 'ينفذ handleSubmit للتحقق والحفظ وفق الحالة الحالية.', constraints: 'لا ترسل أو تحذف بيانات إضافية غير حقول النموذج.', dependencies: [], relatedIds: ['A240'], codeReferences: ['handleSubmit'] }),
  active({ id: 'A250', kind: 'shell', name: 'Scientific Review Workspace', featureId: 'A008', parentId: 'A027', route: '/review', component: 'ReviewPage', sourceFile: 'src/app/(dashboard)/review/page.tsx', description: 'واجهة قائمة مراجعة السجلات العلمية.', behavior: 'تجمع عناصر المراجعة والفلاتر وأدوات التحديث.', constraints: 'تحافظ على مرجع المستند وسياق الآية.', dependencies: ['A251', 'A252'], relatedIds: ['A027'], codeReferences: ['ReviewPage'] }),
  active({ id: 'A251', kind: 'filter', name: 'Review Queue Filters', featureId: 'A008', parentId: 'A250', route: '/review', component: 'ReviewPage', sourceFile: 'src/app/(dashboard)/review/page.tsx', description: 'مرشحات حالة/بحث قائمة المراجعة.', behavior: 'تغيّر عناصر القائمة الظاهرة.', constraints: 'تصفية فقط؛ لا تغير status.', dependencies: ['A252'], relatedIds: ['A250'], codeReferences: ['query', 'status'] }),
  active({ id: 'A252', kind: 'list', name: 'Scientific Review Queue', featureId: 'A008', parentId: 'A250', route: '/review', component: 'ReviewPage', sourceFile: 'src/app/(dashboard)/review/page.tsx', description: 'قائمة السجلات المخصصة للمراجعة.', behavior: 'تتيح عرض التفاصيل والتحديث عبر إجراءات المراجعة الحالية.', constraints: 'لا تُسقط أو تستبدل حالات المراجعة خارج الإجراء المحدد.', dependencies: [], relatedIds: ['A251'], codeReferences: ['review items'] }),
  active({ id: 'A253', kind: 'input', name: 'Review Notes Input', featureId: 'A008', parentId: 'A252', route: '/review', component: 'ReviewPage', sourceFile: 'src/app/(dashboard)/review/page.tsx', description: 'حقل الملاحظات في عنصر المراجعة.', behavior: 'يسجل نص المراجعة المرتبط بالعنصر المحدد.', constraints: 'النص ملاحظة مراجعة ولا يغير محتوى الوجه القرائي.', dependencies: [], relatedIds: ['A252'], codeReferences: ['textarea', 'review note'] }),
  active({ id: 'A254', kind: 'action', name: 'Review Status Action', featureId: 'A008', parentId: 'A252', route: '/review', component: 'ReviewPage', sourceFile: 'src/app/(dashboard)/review/page.tsx', description: 'إجراء تحديث حالة المراجعة.', behavior: 'يحدث حالة العنصر وفق أحد الخيارات المتاحة.', constraints: 'لا يغير الترتيب أو إعداد المحرك.', dependencies: [], relatedIds: ['A252'], codeReferences: ['status action'] }),
  active({ id: 'A260', kind: 'navigation', name: 'Administration Tabs', featureId: 'A009', parentId: 'A028', route: '/admin', component: 'AdminPage', sourceFile: 'src/app/(dashboard)/admin/page.tsx', description: 'تبويبا كتالوج القراءات وإعدادات المحرك القديمة.', behavior: 'يبدل content tab؛ إعداد المحرك يحيل إلى Studio.', constraints: 'يحافظ على توافق المسار القديم دون إنشاء مصدر إعداد ثان.', dependencies: [], relatedIds: ['A261', 'A262', 'A021'], codeReferences: ['TABS', 'setTab'] }),
  active({ id: 'A261', kind: 'list', name: 'Transmission Catalog and Reorder List', featureId: 'A009', parentId: 'A028', route: '/admin', component: 'TransmissionManager', sourceFile: 'src/app/(dashboard)/admin/page.tsx', description: 'قائمة الأئمة والرواة والطرق القابلة للترتيب.', behavior: 'تعرض التسلسل وتدعم السحب وإجراءات التحرير/الحذف.', constraints: 'النقل داخل مجموعة peer فقط؛ لا تغير IDs للقراء أو الرواة أو الطرق.', dependencies: ['A262', 'A263', 'A327'], relatedIds: ['A260'], codeReferences: ['movePeer', 'replacePeers', 'dropOn'] }),
  active({ id: 'A262', kind: 'form', name: 'Transmission Catalog Editor Form', featureId: 'A009', parentId: 'A028', route: '/admin', component: 'TransmissionEditor', sourceFile: 'src/app/(dashboard)/admin/page.tsx', description: 'نموذج إنشاء/تعديل إمام أو راوٍ أو طريق.', behavior: 'يحفظ الكيان المحدد ضمن الكتالوج المحلي.', constraints: 'الحذف المتسلسل يظل مؤكدا ويعرض عدد الكيانات التابعة.', dependencies: ['A327'], relatedIds: ['A261'], codeReferences: ['onSubmit', 'saveTransmissionCatalog'] }),
  active({ id: 'A263', kind: 'drag-handle', name: 'Transmission Reorder Control', featureId: 'A009', parentId: 'A261', route: '/admin', component: 'TransmissionManager', sourceFile: 'src/app/(dashboard)/admin/page.tsx', description: 'سطح السحب لإعادة ترتيب الإمام أو الراوي أو الطريق.', behavior: 'ينقل peer ضمن مجموعته ويعيد ترتيبه صراحة.', constraints: 'لا يغير هوية السجل أو العلاقات الهرمية.', dependencies: [], relatedIds: ['A261'], codeReferences: ['dragProps', 'dropOn', 'movePeer'] }),
  active({ id: 'A270', kind: 'panel', name: 'Settings Workspace', featureId: 'A010', parentId: 'A029', route: '/settings', component: 'SettingsPage', sourceFile: 'src/app/(dashboard)/settings/page.tsx', description: 'محتوى خيارات مساحة العمل.', behavior: 'يعرض إعدادات المستخدم الحالي ومكونات الإدارة.', constraints: 'تغيير القسم لا ينشئ طبقة إعداد جديدة.', dependencies: ['A271'], relatedIds: ['A029'], codeReferences: ['SettingsPage'] }),
  active({ id: 'A271', kind: 'panel', name: 'Strength Degrees Manager', featureId: 'A010', parentId: 'A270', route: '/settings', component: 'StrengthDegreesManager', sourceFile: 'src/components/settings/StrengthDegreesManager.tsx', description: 'قائمة درجات قوة الوجه وإدارتها.', behavior: 'تضيف/تعدل/تعيد ترتيب/تحذف درجات من الكتالوج الحالي.', constraints: 'حافظ على معرفات الدرجات المستخدمة في المستندات.', dependencies: ['A327'], relatedIds: ['A270'], codeReferences: ['useStrengthDegrees', 'strength-degrees'] }),
  active({ id: 'A272', kind: 'action', name: 'Reset Settings Action', featureId: 'A010', parentId: 'A270', route: '/settings', component: 'SettingsPage', sourceFile: 'src/app/(dashboard)/settings/page.tsx', description: 'إجراء إعادة الإعدادات إلى الحالة الافتراضية.', behavior: 'يمر عبر إجراء الصفحة الحالي ورسالة التأكيد عند الحاجة.', constraints: 'لا يحذف مستندات المستخدم أو ملفات المحرك.', dependencies: ['A327'], relatedIds: ['A270'], codeReferences: ['reset'] }),
  active({ id: 'A280', kind: 'panel', name: 'Statistics Dashboard', featureId: 'A011', parentId: 'A030', route: '/statistics', component: 'StatisticsPage', sourceFile: 'src/app/(dashboard)/statistics/page.tsx', description: 'ملخص التغطية والثغرات وتوزيع الفئات والرواة والمستندات.', behavior: 'يعرض المقاييس المستخرجة وروابط الصفحات ذات الصلة.', constraints: 'عرض قراءة فقط؛ لا تستخدم العدادات كمصدر للبيانات.', dependencies: [], relatedIds: ['A030', 'A027'], codeReferences: ['StatisticsPage'] }),
  active({ id: 'A290', kind: 'section', name: 'Public Landing Content', featureId: 'A012', parentId: 'A031', route: '/', component: 'HomePage', sourceFile: 'src/app/page.tsx', description: 'المحتوى الرئيسي للصفحة العامة ومثال التشجير.', behavior: 'يعرض أقسام التسويق وعرضا مبنيا من showcase.', constraints: 'لا تغير المثال إلى mock data.', dependencies: ['A291'], relatedIds: ['A020', 'A022'], codeReferences: ['buildShowcase'] }),
  active({ id: 'A291', kind: 'navigation', name: 'Public Site Navigation', featureId: 'A012', parentId: 'A031', route: '/', component: 'PublicHeader', sourceFile: 'src/components/marketing/PublicHeader.tsx', description: 'روابط التنقل الرئيسية في الموقع العام.', behavior: 'ينقل إلى الصفحات العامة ومساحات العمل.', constraints: 'الروابط وجهات تنقل؛ لا تغير دلالتها عبر تعديل النص فقط.', dependencies: [], relatedIds: ['A020', 'A022', 'A023'], codeReferences: ['NAV_ITEMS'] }),

  // Sign-in form.
  active({ id: 'A340', kind: 'shell', name: 'Local Sign-in Surface', featureId: 'A013', parentId: 'A032', route: '/login', component: 'LoginPage', sourceFile: 'src/app/login/page.tsx', description: 'سطح نموذج الدخول المحلي.', behavior: 'يحيط بالحقول ورسالة التحقق وروابط العودة.', constraints: 'لا يضيف جلسة خادمية أو تدفق مصادقة خارجي.', dependencies: ['A341'], relatedIds: ['A020'], codeReferences: ['handleSubmit'] }),
  active({ id: 'A341', kind: 'form', name: 'Local Sign-in Form', featureId: 'A013', parentId: 'A340', route: '/login', component: 'LoginPage', sourceFile: 'src/app/login/page.tsx', description: 'نموذج البريد وكلمة المرور المحلي.', behavior: 'يتحقق محليا ثم يحفظ بيانات الجلسة المحلية وينتقل للمحرر.', constraints: 'يبقى التنبيه واضحا بأن البيانات لا ترسل لخادم.', dependencies: ['A342', 'A343', 'A344'], relatedIds: ['A032'], codeReferences: ['handleSubmit', 'localStorage'] }),
  active({ id: 'A342', kind: 'input', name: 'Sign-in Email Input', featureId: 'A013', parentId: 'A341', route: '/login', component: 'LoginPage', sourceFile: 'src/app/login/page.tsx', description: 'حقل البريد الإلكتروني.', behavior: 'يخزن قيمة email في حالة النموذج.', constraints: 'لا تحفظ كلمة المرور ضمن الجلسة.', dependencies: [], relatedIds: ['A341'], codeReferences: ['setEmail'] }),
  active({ id: 'A343', kind: 'input', name: 'Sign-in Password Input', featureId: 'A013', parentId: 'A341', route: '/login', component: 'LoginPage', sourceFile: 'src/app/login/page.tsx', description: 'حقل كلمة المرور المحلي.', behavior: 'يستخدم للتحقق المحلي من طول الإدخال.', constraints: 'لا تُرسل القيمة إلى أي API ولا تحفظها في localStorage.', dependencies: [], relatedIds: ['A341'], codeReferences: ['setPassword'] }),
  active({ id: 'A344', kind: 'button', name: 'Local Sign-in Submit Button', featureId: 'A013', parentId: 'A341', route: '/login', component: 'LoginPage', sourceFile: 'src/app/login/page.tsx', description: 'زر إرسال نموذج الدخول المحلي.', behavior: 'يشغل التحقق وحفظ الجلسة في المتصفح.', constraints: 'لا يقدم مصادقة خادمية ولا يرسل بيانات اعتماد.', dependencies: [], relatedIds: ['A341'], codeReferences: ['handleSubmit', 'localStorage.setItem'] }),

  // Shared dashboard shell and confirmation host.
  active({ id: 'A310', kind: 'shell', name: 'Dashboard Layout Shell', featureId: 'A015', parentId: 'A015', route: 'shared-dashboard', component: 'DashboardLayout', sourceFile: 'src/app/(dashboard)/layout.tsx', description: 'غلاف التنقل المشترك لصفحات مساحة العمل.', behavior: 'يرسم Sidebar/Topbar والتنقل المتجاوب ومحتوى route الحالي.', constraints: 'تعديلات الغلاف مشتركة الأثر على جميع dashboard routes.', dependencies: ['A311', 'A313', 'A325', 'A326', 'A327', 'A328'], relatedIds: ['A020', 'A021', 'A022', 'A023'], codeReferences: ['DashboardLayout'] }),
  active({ id: 'A311', kind: 'navigation', name: 'Desktop Sidebar Navigation', featureId: 'A015', parentId: 'A310', route: 'shared-dashboard', component: 'DashboardLayout', sourceFile: 'src/app/(dashboard)/layout.tsx', description: 'قائمة التنقل الجانبية لسطح المكتب.', behavior: 'تفتح مسارات مساحة العمل المتاحة.', constraints: 'تعرض في breakpoint الكبير فقط؛ الوجهات ثابتة من NAV_GROUPS.', dependencies: ['A314', 'A315', 'A316', 'A317', 'A318', 'A319', 'A320', 'A321', 'A327', 'A323', 'A324'], relatedIds: ['A313'], codeReferences: ['NAV_GROUPS'] }),
  active({ id: 'A312', kind: 'navigation', name: 'Dashboard Home Link', featureId: 'A015', parentId: 'A311', route: 'shared-dashboard', component: 'DashboardLayout', sourceFile: 'src/app/(dashboard)/layout.tsx', description: 'رابط العودة إلى الصفحة الرئيسية من القائمة الجانبية.', behavior: 'ينقل المستخدم إلى /.', constraints: 'لا يعدل حالة صفحة أو مستند.', dependencies: ['A031'], relatedIds: ['A311'], codeReferences: ['href=/'] }),
  active({ id: 'A313', kind: 'navigation', name: 'Mobile Workspace Navigation', featureId: 'A015', parentId: 'A310', route: 'shared-dashboard', component: 'DashboardLayout', sourceFile: 'src/app/(dashboard)/layout.tsx', description: 'قائمة التنقل الأفقية على الشاشات الصغيرة.', behavior: 'تتيح فتح المسارات نفسها المعروضة في Sidebar.', constraints: 'تصميم responsive لنفس وجهات NAV_GROUPS؛ لا تنشئ route IDs بديلة.', dependencies: ['A314', 'A315', 'A316', 'A317', 'A318', 'A319', 'A320', 'A321', 'A327', 'A323', 'A324'], relatedIds: ['A311'], codeReferences: ['NAV_GROUPS.flatMap'] }),
  active({ id: 'A314', kind: 'navigation', name: 'Editor Navigation Link', featureId: 'A015', parentId: 'A311', route: 'shared-dashboard', component: 'DashboardLayout', sourceFile: 'src/app/(dashboard)/layout.tsx', description: 'رابط التنقل إلى المحرر.', behavior: 'يفتح /editor.', constraints: 'قد يظهر عنصر responsive مكرر بذات UI ID؛ استخدم route كوجهة.', dependencies: ['A020'], relatedIds: ['A311', 'A313'], codeReferences: ['href=/editor'] }),
  active({ id: 'A315', kind: 'navigation', name: 'Studio Navigation Link', featureId: 'A015', parentId: 'A311', route: 'shared-dashboard', component: 'DashboardLayout', sourceFile: 'src/app/(dashboard)/layout.tsx', description: 'رابط التنقل إلى استوديو المحرك.', behavior: 'يفتح /studio.', constraints: 'لا يعدل إعداد المحرك.', dependencies: ['A021'], relatedIds: ['A311', 'A313'], codeReferences: ['href=/studio'] }),
  active({ id: 'A316', kind: 'navigation', name: 'Variant Index Navigation Link', featureId: 'A015', parentId: 'A311', route: 'shared-dashboard', component: 'DashboardLayout', sourceFile: 'src/app/(dashboard)/layout.tsx', description: 'رابط فهرس الاختلافات.', behavior: 'يفتح /variants.', constraints: 'تنقل فقط.', dependencies: ['A024'], relatedIds: ['A311', 'A313'], codeReferences: ['href=/variants'] }),
  active({ id: 'A317', kind: 'navigation', name: 'Tracking Navigation Link', featureId: 'A015', parentId: 'A311', route: 'shared-dashboard', component: 'DashboardLayout', sourceFile: 'src/app/(dashboard)/layout.tsx', description: 'رابط التتبع.', behavior: 'يفتح /tracking.', constraints: 'تنقل فقط.', dependencies: ['A023'], relatedIds: ['A311', 'A313'], codeReferences: ['href=/tracking'] }),
  active({ id: 'A318', kind: 'navigation', name: 'Quran Navigation Link', featureId: 'A015', parentId: 'A311', route: 'shared-dashboard', component: 'DashboardLayout', sourceFile: 'src/app/(dashboard)/layout.tsx', description: 'رابط المصحف في مجموعة المعرفة.', behavior: 'يفتح /quran.', constraints: 'لا يحمل تغييرا في المستند.', dependencies: ['A022'], relatedIds: ['A311', 'A313'], codeReferences: ['href=/quran'] }),
  active({ id: 'A319', kind: 'navigation', name: 'Qiraat Navigation Link', featureId: 'A015', parentId: 'A311', route: 'shared-dashboard', component: 'DashboardLayout', sourceFile: 'src/app/(dashboard)/layout.tsx', description: 'رابط القراءات.', behavior: 'يفتح /qiraat.', constraints: 'تنقل فقط.', dependencies: ['A025'], relatedIds: ['A311', 'A313'], codeReferences: ['href=/qiraat'] }),
  active({ id: 'A320', kind: 'navigation', name: 'Readers Navigation Link', featureId: 'A015', parentId: 'A311', route: 'shared-dashboard', component: 'DashboardLayout', sourceFile: 'src/app/(dashboard)/layout.tsx', description: 'رابط القراء والرواة.', behavior: 'يفتح /readers.', constraints: 'تنقل فقط.', dependencies: ['A026'], relatedIds: ['A311', 'A313'], codeReferences: ['href=/readers'] }),
  active({ id: 'A321', kind: 'navigation', name: 'Review Navigation Link', featureId: 'A015', parentId: 'A311', route: 'shared-dashboard', component: 'DashboardLayout', sourceFile: 'src/app/(dashboard)/layout.tsx', description: 'رابط المراجعة العلمية.', behavior: 'يفتح /review.', constraints: 'تنقل فقط.', dependencies: ['A027'], relatedIds: ['A311', 'A313'], codeReferences: ['href=/review'] }),
  active({ id: 'A322', kind: 'navigation', name: 'Statistics Navigation Link', featureId: 'A015', parentId: 'A311', route: 'shared-dashboard', component: 'DashboardLayout', sourceFile: 'src/app/(dashboard)/layout.tsx', description: 'رابط الإحصاءات.', behavior: 'يفتح /statistics.', constraints: 'تنقل فقط.', dependencies: ['A030'], relatedIds: ['A311', 'A313'], codeReferences: ['href=/statistics'] }),
  active({ id: 'A323', kind: 'navigation', name: 'Administration Navigation Link', featureId: 'A015', parentId: 'A311', route: 'shared-dashboard', component: 'DashboardLayout', sourceFile: 'src/app/(dashboard)/layout.tsx', description: 'رابط لوحة الإدارة.', behavior: 'يفتح /admin.', constraints: 'تنقل فقط.', dependencies: ['A028'], relatedIds: ['A311', 'A313'], codeReferences: ['href=/admin'] }),
  active({ id: 'A324', kind: 'navigation', name: 'Settings Navigation Link', featureId: 'A015', parentId: 'A311', route: 'shared-dashboard', component: 'DashboardLayout', sourceFile: 'src/app/(dashboard)/layout.tsx', description: 'رابط الإعدادات.', behavior: 'يفتح /settings.', constraints: 'تنقل فقط.', dependencies: ['A029'], relatedIds: ['A311', 'A313'], codeReferences: ['href=/settings'] }),
  active({ id: 'A325', kind: 'navigation', name: 'Quran Quick Link in Workspace Header', featureId: 'A015', parentId: 'A310', route: 'shared-dashboard', component: 'DashboardLayout', sourceFile: 'src/app/(dashboard)/layout.tsx', description: 'رابط سريع إلى المصحف في رأس مساحة العمل.', behavior: 'يفتح /quran.', constraints: 'لا يتغير مصدر تشجير المصحف.', dependencies: ['A022'], relatedIds: ['A318'], codeReferences: ['href=/quran'] }),
  active({ id: 'A326', kind: 'control', name: 'Local Session Badge', featureId: 'A015', parentId: 'A310', route: 'shared-dashboard', component: 'SessionBadge', sourceFile: 'src/components/layout/SessionBadge.tsx', description: 'شارة حالة الجلسة المحلية.', behavior: 'تعرض الدخول المحلي أو اسم المستخدم المحلي وروابطه.', constraints: 'لا توحِ بمصادقة خادمية غير موجودة.', dependencies: [], relatedIds: ['A032'], codeReferences: ['SessionBadge'] }),
  active({ id: 'A327', kind: 'dialog', name: 'Shared Confirmation Dialog Host', featureId: 'A015', parentId: 'A310', route: 'shared-dashboard', component: 'ConfirmDialogHost', sourceFile: 'src/components/ui/ConfirmDialogHost.tsx', description: 'مضيف الحوارات المشتركة للتأكيد الكمي والعمليات الحساسة.', behavior: 'يعرض طلب confirmAction الحالي ويرجع قرار المستخدم إلى المستدعي.', constraints: 'لا ينفذ business operation بنفسه؛ تبقى عواقب العملية عند المكون المستدعي.', dependencies: [], relatedIds: ['A333', 'A152', 'A169', 'A261'], codeReferences: ['confirm-store', 'confirmAction'] }),
  active({ id: 'A328', kind: 'navigation', name: 'Workspace Brand Home Link', featureId: 'A015', parentId: 'A310', route: 'shared-dashboard', component: 'DashboardLayout', sourceFile: 'src/app/(dashboard)/layout.tsx', description: 'رابط شعار مساحة العمل للعودة إلى الصفحة الرئيسية.', behavior: 'ينقل من الشعار المكتبي أو شعار الجوال إلى /.', constraints: 'نسختان responsive للمفهوم نفسه؛ ميّزهما بـ data-ui-instance=desktop-brand/mobile-brand.', dependencies: ['A031'], relatedIds: ['A310', 'A312'], codeReferences: ['TashjirMark', 'href=/'] }),
  active({ id: 'A410', kind: 'inspector', name: 'Developer Registry Inspector Toggle', featureId: 'A014', parentId: 'A014', route: 'development-only', component: 'UIRegistryInspector', sourceFile: 'src/components/dev/UIRegistryInspector.tsx', description: 'زر تفعيل/إيقاف واجهة الفحص.', behavior: 'يفتح طبقة إظهار معرفات DOM ويمكن تفعيله باختصار Alt+Shift+I.', constraints: 'لا يظهر إلا عند NODE_ENV=development ولا يغيّر حالة التطبيق.', dependencies: ['A411', 'A412'], relatedIds: ['A014'], codeReferences: ['process.env.NODE_ENV', 'Alt+Shift+I'] }),
  active({ id: 'A411', kind: 'inspector', name: 'Developer UI ID Overlay', featureId: 'A014', parentId: 'A014', route: 'development-only', component: 'UIRegistryInspector', sourceFile: 'src/components/dev/UIRegistryInspector.tsx', description: 'طبقة شارات مواضع عناصر data-ui-id.', behavior: 'تحدد عناصر DOM المسجلة وتعرض معرف كل منها فوق مكانها.', constraints: 'تستثني عناصر inspector نفسها ولا تعترض أحداث عنصر التطبيق الأصلي.', dependencies: ['A410'], relatedIds: ['A412'], codeReferences: ['document.querySelectorAll([data-ui-id])'] }),
  active({ id: 'A412', kind: 'inspector', name: 'Developer Registry Details Card', featureId: 'A014', parentId: 'A014', route: 'development-only', component: 'UIRegistryInspector', sourceFile: 'src/components/dev/UIRegistryInspector.tsx', description: 'بطاقة تفاصيل عنصر Registry المحدد.', behavior: 'تعرض النوع والميزة والأب والمسار والمكون والملف والغرض والسلوك والقيود والاعتماديات.', constraints: 'مصدر التفاصيل هو سجل TypeScript؛ لا يقرأ أو يغير business state.', dependencies: ['A410'], relatedIds: ['A411'], codeReferences: ['getUIIdentity', 'getFeatureById'] }),
] as const satisfies readonly UIRegistryEntry[];

/** IDs already retired before this registry was introduced. Append only; never reuse. */
export const RETIRED_UI_IDS: readonly string[] = [];

export type RegistryIdentity = (typeof FEATURE_REGISTRY)[number] | (typeof UI_REGISTRY)[number];

export function getUIEntryById(id: string): (typeof UI_REGISTRY)[number] | undefined {
  return UI_REGISTRY.find((entry) => entry.id === id);
}

export function getUIIdentity(id: string): RegistryIdentity | undefined {
  return getUIEntryById(id) ?? FEATURE_REGISTRY.find((feature) => feature.id === id);
}

export function getFeatureForIdentity(id: string) {
  const identity = getUIIdentity(id);
  return identity ? FEATURE_REGISTRY.find((feature) => feature.id === ('featureId' in identity ? identity.featureId : identity.id)) : undefined;
}
